version: "3.9"
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_HOST_AUTH: trust
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myUser:myPassword@db:5432/postgres?connect_timeout=1000
    ports:
      - "3030:3030"
    command: bash -c "sleep 60 && npx prisma migrate dev"

volumes:
  pgdata: